-- CreateEnum
CREATE TYPE "BillingSource" AS ENUM ('APPLE_APP_STORE', 'GOOGLE_PLAY', 'MERCHANT_WEBSITE', 'IN_APP_DIRECT', 'E_WALLET', 'CARD_OR_BANK', 'TELCO_BUNDLE', 'INVOICE_MANUAL', 'UNKNOWN');

-- AlterTable
ALTER TABLE "Subscription" ADD COLUMN "billingSource" "BillingSource" NOT NULL DEFAULT 'UNKNOWN';
